Opetushallitus/koto-rekisteri

- .github/workflows/playwright.yml
- e2e/.gitignore
- e2e/package-lock.json
- e2e/package.json
- e2e/playwright.config.ts
- e2e/tests/hello.spec.ts
- frontend/next.config.mjs
- frontend/src/pages/hello-playwright.tsx
- frontend/tsconfig.json
- server/src/main/kotlin/fi/oph/kitu/auth/WebSecurityConfig.kt
Add Playwright for e2e-tests, and an unsecured endpoint for a "hello, world" type of test
> Add e2e tests

- .github/workflows/build.yml
- infra/bin/infra.ts
- infra/lib/certificate-stack.ts
- infra/lib/dns-stack.ts
- infra/lib/infra-stack.ts
> feat(infra): add DNS and certificate stacks

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/playwright.yml
- .github/workflows/test.yml
- .run/npm run dev.run.xml
- Dockerfile
- README.md
- frontend/next.config.mjs
- scripts/build_frontend.sh
- server/pom.xml
Node ajetaan erillisenä spring bootista. Sen lisäksi lisätty `.run` - kansioon konfiguraatio, jolla voi ajaa nodea ideasta
> fix: pipeline

- .github/workflows/build.yml
- .github/workflows/test.yml
The test job builds the frontend anyway.
> Remove redundant frontend builds from CI

- server/src/test/kotlin/fi/oph/kitu/test/DBFixture.kt
This is a slightly better/more correct/my preference for cleaning the database for each test.
> Run migrations before each test

- .github/workflows/_deploy-env.yml
Reverts Opetushallitus/koto-rekisteri#167
> Revert "chore: try being non-exclusive"

- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application-untuva.properties
Etunollat on välillä vaikeita muistaa.
> Fix: Malformed daily schedule configuration

- .github/renovate.json
> keep 'ref:' - prefix in renovate

- .github/renovate.json
https://github.com/Opetushallitus/koto-rekisteri/issues/310
> fix(.github): renovate regex

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
> refactor: add withEvent helper

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaSuorituksetResponse.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
Also, print the original exception when trying to handle a MoodleError and that fails
> feat: parse new koealusta suoritukset response

- server/pom.xml
While looking at #416 I noticed I've added these dependencies when adding testcontainers. I don't remember what these are for or why I added them, so let's see if we can just remove them.
> chore: remove weird dependencies

- server/src/main/kotlin/fi/oph/kitu/yki/YkiController.kt
- server/src/main/resources/templates/index.html
- server/src/main/resources/templates/yki-arvioijat.html
Lisätty näkymä, jossa listattuna YKI:sta tuodut arvioijat.
> Add view for YKI arvioijat

- scripts/check_env-vars.sh
- scripts/start_database_docker.sh
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/YleistunnisteHae.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/YleistunnisteHaeRequest.kt
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application.properties
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceMock.kt
- server/src/test/resources/application.properties
Can be tested with instructions of https://github.com/Opetushallitus/koto-rekisteri/pull/400
> feat(kotoutumiskoulutus/oppijanumero): get oid for koealusta user from ONR

- server/src/main/kotlin/fi/oph/kitu/generated/api/YkiControllerApi.kt
I added auto-merge to https://github.com/Opetushallitus/koto-rekisteri/pull/452 without realizing it will merge even if the checks fail
> chore: regenerate sources

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
Haetaan OID jokaiselle käyttäjälle erikseen, riippumatta vastauksista.
Huom! Meillä on vielä työn alla batchaus tehtävä, jota ei tehdä tässä PR:ssä.
> feat(koealusta): get oid per user, not per completition

- server/src/main/resources/application-e2e.properties
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application-untuva.properties
- server/src/main/resources/application.properties
- enable scheduled imports
- remove test urls form `application.properties` and explicitly include them in environments where needed
> Fix application-prod.properties

- server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
This removes warnings in IDEA and adds documentation to the properties.
> feat: define our custom spring properties

- server/src/main/resources/application-untuva.properties
Error: `Unrecognized schedule: 'FIXED_DELAY|1h'. Parsable examples: [FIXED_DELAY|120s, DAILY|12:00, DAILY|12:00,13:45, DAILY|12:00,13:45|Europe\/Rome, -]`
> fix: fixed delay doesn't support hours?

- server/src/main/resources/application-qa.properties
> fix: slower koealusta import schedule on QA

- .github/renovate.json
Tämän jälkeen mm. mergettäis automaattisesti
> feat(.github): set automerge on mise patches

- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application.properties
Oppijanumerorekisterille lähetettäviin kutsuihin lisättävä kutsujan tunniste kaikissa ympäristöissä suosituksen mukaiseksi.
> Use a more descriptive ONR caller id in all envs

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasException.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
Because it means that oppija is not found
> feat(koto): handle when yleistunniste/hae returns 404

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroException.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/YleistunnisteHae.kt
- server/src/main/resources/application.properties
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedServiceMock.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/HttpResponseMock.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
- server/src/test/resources/application.properties
throws OppijaNotFoundException if oppija is not found
throws OppijaNotIdentifiedException if oppija is missing oppijanumero from oppijanumero-service call yleistunniste/hae.
> fix(oppijanumero): handle oppijanumero errors

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/MoodleException.kt
- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/test/kotlin/fi/oph/kitu/logging/LoggerExtensionsTests.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockEvent.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockLogger.kt
Kotlinissa [Throwable](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/-throwable/) on kaikkien virheiden base class, eikä `Exception`, niinkuin javassa.
> fix(logging): catch errors properly

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
Lisätty joitain arvoja, jotka vihjaa siitä minkälainen response on tullut oppijanumerorekisterista (`yleistunniste/hae`).
> feat(oppijanumero): improve logging

- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaRepository.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiArvioijaRepositoryTest.kt
- `batchUpdate`n käyttöä piti muokata, jotta päivitettyjen rivien id:t saa talteen KeyHolderiin ja niiden perusteella voi hakea kannasta ainoastaan tallennetut rivit.
- eriytin tallennettujen rivien haun omaksi (priva) funktiokseen, jotta se vähän selkeyttäisi tuota saveAll-funktiota
> fix: yki arvioijat saveAll returns only the saved arvioijat

- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusMappingService.kt
Hyväksytään rajapinnasta sukupuoli-kentästä tyhjä arvo, ja mäpätään se meillä `E`:ksi.
> Handle null sukupuoli values received from api

- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaRepository.kt
Palautetaan käyttöliittymälle arvioijat järjestyksessä niin, että viimeksi lisätyt on ensimmäisenä.
> Sort arvioijat by rekisteriintuontiaika

- infra/lib/log-groups-stack.ts
N.B. The "audit" in the name of this feature has no relation to our audit log group.
> feat: log data protection audits to cloudwatch

- e2e/models/yki/YkiSuorituksetPage.ts
- e2e/tests/yki/yki-suoritukset.spec.ts
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusRepository.kt
- server/src/main/resources/templates/yki-suoritukset.mustache
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
Haku mätsää seuraaviin kenttiin:
- oppijanumero
- henkilötunnut
- etunimet
- sukunimi
- sähköposti
- järjestäjän oid
- järjestäjän nimi
Simppeli haku, joka vertaa hakuehtoa yksittäin kenttiin, eli esim. haku etu- **ja** sukunimellä ei tässä toteutuksessa vielä toimi.
> YKI suoritukset search

- scripts/stop_tmux.sh
> feat(script): quit tmux faster

- server/pom.xml
Fixes: https://github.com/Opetushallitus/koto-rekisteri/security/dependabot/27
> fix: netplex JSON vulnerability in test code

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiScheduledTasks.kt
Nopea refaktorointi, käytetään samaa parsintalogiikkaa kaikille ajastetuille tehtäville.
> Use lenient schedule parsing for all tasks

- infra/lib/service-stack.ts
Reverts Opetushallitus/koto-rekisteri#915
> Revert "Make deploys faster"

- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
otherwise oldest lastModified date
> feat(yki): use newest lastModified date if no errors

- server/src/main/resources/templates/yki-suoritukset.mustache
> fix(yki): close a-tag properly

- server/src/main/kotlin/fi/oph/kitu/dev/YkiController.kt
- server/src/main/resources/application-e2e.properties
- server/src/main/resources/application-local.properties
In the local and e2e environments, a local controller will be used instead of the actual endpoint.
> feat(yki): add endpoint for e2e - tests

- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvExportError.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorMappingService.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
Also a bug fix. Katso muut kommentit ->
> fix(yki-suoritus-error): validation error is log and not stored in the logs

- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
Pieni lipsahdus aikaisemmissa refaktoroinneissa.
> fix: testi user oid accidentally same as ranja

- README.md
Idea herjaa näistä nullable - kentistä. ~Mistä se johtuu? Onko tämä korjaus oikea ratkaisu?~
Tämä tulee, jos [K2 mode](https://blog.jetbrains.com/idea/2024/11/k2-mode-becomes-stable/)a ei ole laitettu päälle
> fix(kotoutumiskoulutus): fix errors

- server/src/test/kotlin/fi/oph/kitu/logging/MockTracer.kt
> fix: remove TODOs

- server/src/main/resources/templates/yki-arvioijat-virheet.mustache
> fix(yki): remove extra lastModified in arvioija-errors

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
Virhe ei johdu datasta, joten pitää heittää tavallinen virhe
> fix(oppijanumero): throw OppijanumeroException

- server/src/main/kotlin/fi/oph/kitu/TypedResult.kt
- server/src/main/kotlin/fi/oph/kitu/logging/OpenTelemetryExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasError.kt
> feat: show TypedResult.Failure as Error in OpenTelemetry traces

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/TypedResultExtensions.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceMock.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
> feat(koto): show moodleid on oppijanumero errors

- server/src/main/kotlin/fi/oph/kitu/webmvc/WebConfig.kt
I didn't know how Spring conversions work. Thank you @Kailari!
> Fix koto errors sorting for real this time

- server/src/main/resources/db/migration/V36__drop_teacher_results_from_koto_suoritus.sql
- server/src/main/resources/templates/koto-kielitesti-suoritukset.mustache
Also fix casing in koto suoritukset details view titles
> Remove old columns from koto_suoritus

- server/src/main/resources/templates/koto-kielitesti-suoritukset.mustache
Poistetaan turhaa hässäkkää suoritukset-sivulta.
> Remove UI text related to old grade system

- infra/lib/service-stack.ts
Ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/README.md
> Allow EMF export

- e2e/models/vkt/VktIlmoittautuneetPage.ts
- e2e/tests/vkt/vkt-suoritukset.spec.ts
- e2e/util/expect.ts
- server/src/main/kotlin/fi/oph/kitu/html/Page.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/SearchQueryParser.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepository.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktSearch.kt
- **Disable dark mode form PicoCSS**
- **Support search by tutkintopäivä**
- **Add tests for VKT search**
> OPHKOTO-15: VKT-suoritusten haku tutkintopäivällä

- server/src/main/kotlin/fi/oph/kitu/i18n/LocalizationService.kt
- server/src/main/kotlin/fi/oph/kitu/koodisto/KoodistoService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepository.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusService.kt
> feat(vkt): add more tracing

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasService.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/MockRestServiceServerExtensions.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
- server/src/test/resources/application.properties
Tää on vielä vähän ikävä, kun en pysty käyttämään spring-frameworkkia. Jos joku springboot guru keksis, miten sen sais tähän, niin nää testit vois yhdistää kotoutumiskoulutustestien kanssa.
> wip: cas login-flow

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvParser.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/OpenTelemetryExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/i18n/LocalizationService.kt
- server/src/main/kotlin/fi/oph/kitu/koodisto/KoodistoService.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiScheduledTask.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiService.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/tehtavapankki/TehtavapankkiScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/tehtavapankki/TehtavapankkiService.kt
- server/src/main/kotlin/fi/oph/kitu/observability/OpenTelemetryExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/observability/OpenTelemetrySamplingRules.kt
- server/src/main/kotlin/fi/oph/kitu/observability/OpenTelemetryTracerConfig.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/error/YkiArvioijaErrorService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
OPHKOTO-4
This should reduce our traces in CloudWatch substantially and make it easier to use observability tools to diagnose problems.
> OPHKOTO-4: Sample health checks at 1%

- server/src/main/kotlin/fi/oph/kitu/html/DisplayTable.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuorituksetPage.kt
> fix: wide content in yki-suoritukset page

- e2e/fixtures/baseFixture.ts
- e2e/fixtures/ykiArvioija.ts
- e2e/models/yki/YkiArvioijatPage.ts
- e2e/tests/yki/yki-arvioijat.spec.ts
- server/src/main/kotlin/fi/oph/kitu/dev/CreateMockDataController.kt
- server/src/main/kotlin/fi/oph/kitu/mock/YkiArvioijaErrorMock.kt
- server/src/main/kotlin/fi/oph/kitu/mock/YkiArvioijaMock.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaPage.kt
- Yki arvioijat -sivun breadcrubs korjattu
- Pari playwright-testiä arvioijat-sivulle ja arvioijien järjestämiselle sukunimen mukaan
> Yki arvioijat e2e tests

- infra/lib/accounts.ts
- infra/lib/environment-stage.ts
- infra/lib/service-stack.ts
- server/src/main/resources/application-e2e.properties
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application-untuva.properties
- server/src/main/resources/application.properties
- siirretty `server.servlet.context-path=/kielitutkinnot` ympäristöjen jakamaan `application.properties`iin
- poistettu #1538 lisätyt eritellyt health check pathit nyt kun ne on kaikissa ympäristöissä sama
> Update prod appUrl

- e2e/models/kotoutumiskoulutus/KielitestiSuorituksetPage.ts
- e2e/tests/kotoutumiskoulutus/kielitesti-suoritukset.spec.ts
- server/src/main/kotlin/fi/oph/kitu/html/Navigation.kt
Kotoutumiskoulutuksen kielikokeet --> Kotoutumiskoulutuksen kielitaidon päättötesti
> Fix koto kielitesti texts

- server/src/main/kotlin/fi/oph/kitu/html/ViewMessage.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktErinomaisenArviointiPage.kt
- server/src/main/resources/static/style.css
- **Common component to show user messages after redirection**
- **Show a success message after save**
> OPHKOTO-15: Näytä viesti onnistuneesta tallentamisesta

- server/src/main/kotlin/fi/oph/kitu/html/ViewMessage.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/resources/static/style.css
- **Remove comment containing obsolete code**
- **Use correct css class names**
> OPHKOTO-15: Korjaa ilmoituslaatikon väri

- server/pom.xml
Fixes https://github.com/Opetushallitus/koto-rekisteri/security/dependabot/45
> fix dependabot-45

- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/MockOppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
- **Korjaa json-parsinta**
- **Käytä default object mapperia onr-clientissä**
> Korjaa json-parsinta, osa 2

- server/src/main/kotlin/fi/oph/kitu/koodisto/Koodisto.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepository.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritus.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusEntity.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktErinomaisenArviointiPage.kt
- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application-untuva.properties
- server/src/main/resources/application.properties
- server/src/main/resources/db/migration/V45__add_merkitty_poistettavaksi_to_vkt_suoritus.sql
- server/src/main/resources/db/migration/V56__add_cascading_rules_to_vkt_suoritus.sql
- server/src/test/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepositoryTest.kt
- server/src/test/resources/application.properties
- **Mahdollista vkt-osakokeen merkintä ei-suoritetuksi**
- **Poista merkityt osakokeet skedulerilla**
- **Poista vkt-suoritukset, joilla ei ole enää osakokeita**
> OPHKOTO-61: No show -tapausten käsittely vkt-erinomaiselle

- server/src/main/kotlin/fi/oph/kitu/koski/KoskiService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktKoskiErrors.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktSuorituksenTiedot.kt
- **Älä merkitse käsitellyksi suoritusta, joka vielä odottaa korjausta**
- **Näytä tieto virheellisestä tilasta tietokannassa**
> Lisää KOSKI-korjauksia
