- infra/lib/infra-stack.ts
Change this to HTTPS once we have certificates for ALBs. Let's do the DB first.
> Use HTTP for ALBs

- scripts/start_local_env.sh
importtasin scriptin repoon (mun .zhsrc:sta), jolla laitan itselleni devausympäristön pystyyn.  Tämän lisäks, tämänkin jälkeen, i mulla on mun `~/.zshrc` - tiedostossa:
```zsh
alias idea='/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea'
eval "$(mise activate zsh)"
kotorekisteri-start-tmux() {
(
cd $KOTO_REKISTERI
./scripts/start_local_env.sh $KOTO_REKISTERI
)
}
```
Mun scripti käyttää https://github.com/tmux/tmux - Session manageria käynnistämään yhtä aikaa useita shell instasseja. Instassit, eli ikkunat:
- 0: database: Ajaa tietokannan dockerissa, sekä ajaa migraatiot
- 1: idea: Käynnistää idean 
- 2: springboot: Ajaa springbootin
- 3: workspace: Näyttää gitin ja repon juuren tiedostot
> feat: start local env

- Dockerfile
Running `tree` in the Docker build prints thousands of lines of output. It's not needed now.
> chore: remove unnecessary commands from docker build

- .github/workflows/build.yml
Let the top level workflow start concurrently so that while an older workflow is deploying to test, a newer one can already start deploying to dev, instead of having to wait for the old workflow to complete.
> chore: try concurrent deploys

- .github/workflows/codeql.yml
This is needed to specify a newer version of the JDK - let's see if this works.
> Configure java/kotlin CodeQL scanning manually

- infra/bin/infra.ts
- infra/lib/certificate-stack.ts
- infra/lib/infra-stack.ts
It's really difficult to secure CloudFront -> ALB communication so that only CF is allowed to call the ALB. Instead of doing that, let's just remove CloudFront for now.
> fix: remove CloudFront

- .github/workflows/deploy-env.yml
This is just to enforce the versions of any tools like npm we use.
> chore: use mise in deploy jobs

- .mise.toml
We force mise to build awscli from source because otherwise it would use the x86_64 binary distribution even on ARM Macs.
> chore: add awscli to mise

- server/pom.xml
Spring automatically runs migrations if the appropriate flyway dependency is in classpath when the app starts. This PR moves the flyway core package from the `test` scope to the main scope so it's in classpath.
> fix: run flyway migrations when app starts up

- server/src/main/resources/application-local.properties
Tämä arvo kuuluu tulla `local.properties`-tiedostosta lokaaliympäristössä, joten poistetaan `application-local.properties` viittaus ympäristömuuttujaan jota ei ole tarkoituskaan käyttää.
> fix: oppijanumero password in local env

- server/src/main/resources/static/open-api.yaml
```
[INFO] --- openapi-generator:7.8.0:generate (default) @ kitu ---
[INFO] Generating with dryRun=false
[INFO] No .openapi-generator-ignore file found.
[INFO] OpenAPI Generator: kotlin-spring (server)
[INFO] Generator 'kotlin-spring' is considered stable.
[INFO] Setup code generator for Kotlin Spring Boot
[INFO] 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[INFO] 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[INFO] writing file /Users/ivacklin/code/koto-rekisteri/server/src/main/kotlin/fi/oph/kitu/generated/model/Oppija.kt
[INFO] Successfully executed: ktlint -F /Users/ivacklin/code/koto-rekisteri/server/src/main/kotlin/fi …
```
> fix: add servers to openapi spec

- server/src/main/kotlin/fi/oph/kitu/auth/WebSecurityConfig.kt
- server/src/main/kotlin/fi/oph/kitu/dev/MockYkiControllerApi.kt
- server/src/main/kotlin/fi/oph/kitu/mock/MockYkiControllerApi.kt
Ajatus on, että on joku mock-rajapinta, jota meidän YKI-api voi kutsua. Ongelma ratkaistu luomalla oma endpoint `api/mock/yki` - joka palauttaa aina samat tiedot
> feat: create a mock api for YKi

- .github/workflows/_deploy-env.yml
- .github/workflows/build.yml
Tämä PR kertoo GitHub Actionsille kohdeympäristöt, jolloin deploymentit tulevat näkyviin myös repon etusivun Deployments-osioon. Tällä hetkellä myös diffit PR:stä tulevat sinne, mikä voi olla joko OK tai turhaa. On vähän hankala kuitenkaan workflow-syntaksilla estää tuota.
> fix: tell GHA where we're deploying again

- infra/lib/log-groups-stack.ts
We don't want to match this:
2024-10-08T19:45:38.572Z INFO 1 --- [kitu] [nio-8080-exec-8] o.apache.coyote.http11.Http11Processor : Error parsing HTTP request header
Also, treat missing data as OK, since metric filters don't output a value when they don't match.
> Match only ERRORs in log alarm

- .github/renovate.json
NPM updates seem to work consistently (unlike mise updates), so let's test automatically merging minor and patch updates if CI passes.
> feat(deps): automatically merge minor npm dependency updates

- .gitignore
- infra/lib/environment-stage.ts
- infra/lib/log-groups-stack.ts
- infra/lib/service-stack.ts
- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/Constants.kt
- server/src/main/kotlin/fi/oph/kitu/logging/CloudWatchAppender.kt
- server/src/main/kotlin/fi/oph/kitu/logging/Logging.kt
- server/src/main/kotlin/fi/oph/kitu/oppija/OppijaService.kt
- server/src/main/resources/logback-spring.xml
Toteutusvaihtoehdot:
- FireLens-sidecar
- Sovellus kirjoittaa itse CloudWatchiin
- OpenTelemetry collector -sidecar (nykyään osaa myös lokeja)
Valitsin tässä yksinkertaisimman eli sen että sovellus itse kirjoittaa audit-lokirivit CloudWatchiin.
Tämä riippuu PR:stä #213 
Esimerkki käytöstä:
https://github.com/Opetushallitus/ludos/blob/efa925c4638a5f86fbb8d1e3c29a4da750f1dd25/server/src/main/kotlin/fi/oph/ludos/auth/CasConfig.kt#L98-L102
> Add audit logging capability

- frontend/package-lock.json
- frontend/package.json
- Duplikaatti pullareille #263 #267 ja #268 
- Pidetään `react@18`, koska `react@19`:sta ei ole tullut vielä stable releasea.
- Ei turbopackkia. Se olis hyvä devaamiseen, mutta meillä on (ainakin toistaiseksi) vain static export ja deployataan nom run build:n avulla.
- https://github.com/vercel/next.js/pull/70480
> Breaking Pages and routes in App Router will no long support export const runtime = "experimental-edge", they will be required to switch to export const runtime = "edge". They were the same here anyways but this stabilizes it.
- https://github.com/vercel/next.js/pull/68812
- https://github.com/vercel/next.js/pull/68379
- Me ei käytetä verceliä, joten meille turha. (Tähän kannattaisi siirtyä jos me päädyttäisiin käyttämään verceliä)
- https://github.com/vercel/next.js/pull/67126
> chore(frontend): upgrade next to version 15

- .github/renovate.json
Only tested dry-run, but not sure yet if this works. Atleast dry-run passes.
> chore(.github): keep 'ref:' - prefix in renovate

- .github/renovate.json
This should fix the following warning (wrong behaviour) found in [Renovate logs](https://developer.mend.io/github/Opetushallitus/koto-rekisteri/-/job/7fcb7fbc-fa8d-4ecc-af0e-0b8a2572d154):
```
WARN: Found renovate config warnings
{
"warnings": [
{
"topic": "Config warning",
"message": "\"fileMatch\" must be configured in a manager block and not here: packageRules[1]"
}
]
}
```
> fix: renovate pom match

- .github/workflows/_deploy-env.yml
- .github/workflows/build.yml
This should allow ubi to make authenticated requests to GitHub and not encounter rate limits.
We should go through the security implications of this before merging.
Fixes #351
> fix: pass GITHUB_TOKEN to mise/ubi

- server/src/main/resources/application-prod.properties
We get spurious alerts from them since we don't have the integration keys yet.
The alternative would be to disable the log alarm in prod.
> chore: disable integrations in prod

- server/src/main/kotlin/fi/oph/kitu/ExternalSystem.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroController.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
refactor logging. In oppijanumero, logs all HTTP responses to the same log event. I recommend to read this commit by commit.
refactor loggin, mostly on oppijaumero.
- replaced `println` from Oppijanumero with `logger.atInfo ... .log()`, since it was already printing each request.
- removed few redundant log row 
- `addResponse` requires now a parameter `ExternalSystem`. This is to tag external systems easier (for example if the message was from CAS or Oppijamumero)
> refactor: improve logging on oppijanumero

- server/pom.xml
- server/src/main/resources/application.properties
- server/src/main/resources/db/migration/V9__create_scheduled_executions_logs_table.sql
The UI is available at $URL/db-scheduler after CAS authentication.
> feat: add scheduler UI

- scripts/ensure_aws_secrets.sh
- scripts/start_local_env.sh
- scripts/start_local_server.sh
- scripts/test_oppijanumerorekisteri.sh
In my setup, I usually do not use `start_local_server.sh`, so want to use the variables outside the script. Also, they were not sourced, so they weren't accessible, atleast for idea's debugger.
> feat(scripts): source aws secrets in start_local_env.sh

- .github/workflows/_deploy-env.yml
- .mise.ci.toml
- infra/lib/db-stack.ts
This allows us to use the Query Editor in AWS Console to e.g. clear the database when testing imports.
I'm not sure if we need to grant access separately to our IAM role - we use AdministratorAccess right now, which should be able to do anything. We can test this in the test environment, which doesn't have the Data API enabled yet (whereas dev does).
> feat: enable RDS Data API

- server/src/main/kotlin/fi/oph/kitu/auth/WebSecurityConfig.kt
Muutin toteutuksen nyt niin että otetaan CSRF-suoja pois päältä näiltä API-endpointeilta.
> fix: db-scheduler-ui run/rerun triggers

- server/src/main/kotlin/fi/oph/kitu/yki/SolkiArvioijaResponse.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiArvioijaEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiRepository.kt
- server/src/main/resources/db/migration/V11__allow_persisting_updates_to_yki_arvioija.sql
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
Muuttaa arvioijien tietojen tuontia siten, että mikäli tiedot ovat päivittyneet, ne lisätään nyt uutena rivinä. Vaihtoehto olisi päällekirjoittaa vanhojen tietojen tilalle, mutta uuden rivin lisääminen on vähemmän peruuttamaton operaatio. Rekisterin käyttötapauksien ollessa vielä hämärän peitossa, myös rekisterin historiatietojen ylläpitäminen tietokannassa on turvallisempi vaihtoehto (päällekirjoitusta ei voi peruuttaa).
Toteutin tämän yksinkertaisesti niin, että `yki_arvioija`:n `UNIQUE` rajoite koskee nyt kaikkia data-sarakkeita, pelkän `arvioijan_oppijanumero` sijaan. Tämä, yhdessä `ON CONFLICT DO NOTHING` kanssa pitäisi saavuttaa se, ettei duplikaatteja rivejä tallenneta, mutta kaikki muuttuneet tiedot persistoidaan.
Jotta uusin rivi olisi helpompaa tunnistaa, lisäsin vielä …
> Import updated arvioija records as separate entries

- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
Muutokset: 
1. Oppijanumero - service voi palauttaa muuta kuin HTTP STATUS 200, esim käyttökatkon aikana. Lisätty tarkastus, että heitetään eksplisiittisesti virhe tälläisissä tilanteissa.
2. Lisätty HTTP status koodi - lokeihin omana keyvalue:na, jotta esim em. virhetilanteet voidaan filtteröidä helpommin
3. ONR mokkaus data aiemmin vain asetti requestiin testikäyttäjän tiedot, jotka lähetettiin ONR:ään. Muutettu, että jos `use-mock-data` - vipu on käytössä, niin ei tehdä pyyntöjä ONR:ään, vaan palautetaan testikäyttäjän tiedot kovakoodatusti rajapinnasta.
> feat: improve logging and mocking with oppijanumero

- server/src/main/resources/static/style.css
- server/src/main/resources/templates/yki-suoritukset.html
- Tarkistusarviointien tiedot mukaan YKI-suorituslistaan
- Suorittajan ja tarkistusarvioinnin tiedot piilotettu details-elementtiin, jotta taulukko ei olisi niiin leveä
- Tarkistusarvioinnin tiedot näkyvät vain jos suorituksella on tarkistusarvioinnin saapumispäivä, tällä hetkellä testiympäristössä millään suorituksella ei sitä ole
- Lisätty _hyvin_ yksinkertainen tyyli, jotta suorituksen tiedot ja suorittajan tiedot on selkeämmin luettavissa yhdeksi riviksi
> Add missing fields to yki suoritus and hide some details

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/logging/AccessLoggingConfiguration.kt
- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/resources/logback-access.xml
logback-access doesn't support Spring's native structured logging. Let's implement our own logger at the Spring request/response lifecycle level instead.
Example:
```json
{
"@timestamp": "2024-11-25T15:27:59.090332Z",
"ecs.version": "8.11",
"http.request.method": "GET",
"http.response.body.size": null,
"http.response.status_code": 200,
"log.level": "INFO",
"log.logger": "fi.oph.kitu.logging.AccessLoggingConfiguration$logFilter$1",
"message": "HTTP GET http://localhost:8080/yki/arvioijat",
"process.pid": 11369,
"process.thread.name": "http-nio-8080-exec-3",
"service.name": "kitu",
"url.path": null,
"url.query": "continue",
"url.scheme": "http",
"user_agent.original": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
} …
```
> fix: use a custom HTTP access logger, again

- infra/lib/accounts.ts
- infra/lib/db-stack.ts
- infra/lib/environment-stage.ts
Slight issue here related to Aurora clusters and how CDK models them (wrongly): https://github.com/aws/aws-cdk/issues/26726 - this means that if the cluster failovers, our "reader" replica can become the writer. CDK will be confused on the next run (since the writer has disappeared). I'm not sure what CDK will do in that case, we should test it.
```
Resources
[+] AWS::RDS::DBInstance Database/DbStack/reader DbStackreader1001C220
[~] AWS::RDS::DBCluster Database/DbStack DbStackBE19CDA3
├─ [+] DeletionProtection
│   └─ true
├─ [+] PerformanceInsightsEnabled
│   └─ true
└─ [+] PerformanceInsightsRetentionPeriod
└─ 7
```
> feat: add production quality features to rds db

- e2e/tests/yki-suoritukset.spec.ts
- server/src/main/kotlin/fi/oph/kitu/ResultSetExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvMapping.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/OidSerializer.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/SolkiArvioijaResponse.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaRepository.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusRepository.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
- Uudelleennimetty `SolkiSuoritusResponse`, koska sitä käytetään tässä myös csv:n luonnissa eikä nimi ollut enää niin kuvaava (en halunnut luoda uutta luokkaa csv:n luomista varten, koska ainakin tässä vaiheessa se olisi identtinen tämän olemassaolevan luokan kanssa)
- Voidaan miettiä uudelleen, jos halutaan että csv-export eroaa siitä mitä meille rajapinnasta tulee
- csv:n sarakkeet tulevat nyt samassa järjestyksessä, kuin Solkin YKI-rajapinnassa, eivätkä enää aakkosjärjestyksessä
- Aikaleimat ja päivämäärät parsitaan samassa muodossa meidän csv-exportiin kuin mitä ne ovat Solkin YKI-rajapinnassa
> Fix CSV export date and timestamp formatting and header order

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/logging/LoggerExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceMock.kt
- Helpointa lukea varmaan katsomalla ensin vanha toteutus ja sitten uusi.
- Toteutettu refaktoroimalla yleisTunnisteHae - metodi, se on uudelleenimetty getOppijanumero.
- Lisätty samalla metodiin lokitusta
- Jos code quality:stä haluaa nillittää, niin tuossa metodissa tehdään nyt kaksi asiaa, oid tarkastus ja kutsu `/yleistunniste/hae` - endpointtiin. Vois olla siistimpi, että ne on eri metodeissa, mutta en jaksanut miettiä sitä.
- [lisätty](https://github.com/Opetushallitus/koto-rekisteri/pull/521/commits/b3d0b9ecfc45351b58f25edba800fd6f330f76ac) `event.addCondition` - helpperi, jota käytän niin, että se lokittaa aina attribuutin, ja jos se on `true`, niin lopetetaan metodin suorittaminen. Tarkoituksena lyhentää koodirivien määrää.
> feat(koto): use oppijanumero instead of oid

- infra/lib/log-groups-stack.ts
Pitäisi piilottaa hetut lokeista
https://blog.awsfundamentals.com/masking-sensitive-data-with-amazon-cloudwatch-logs-data-protection-policies#heading-understanding-data-protection-policies
> feat(infra): add data protection policy to mask finnish SSN from logs

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiSuoritus.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/resources/db/migration/V17__koto_rename_oid_to_oppijanumero.sql
rename oppija oid to oppijanumero, because we save oppijanumero, not oppija oid.
> refactor(koto): rename oppija oid to oppijanumero

- server/src/main/kotlin/fi/oph/kitu/csvparsing/TutkintokieliDeserializer.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/yki/BooleanFromNumericDeserializer.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/yki/TutkintokieliDeserializer.kt
- server/src/main/kotlin/fi/oph/kitu/yki/Tutkintokieli.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/SolkiArvioijaResponse.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
> Tutkintokielissä on historiallisista syistä muutama ei-ISO-muotoinen kielikoodi:
> 10,Svenska,svenska,Swedish
> 11,Kaupallinen englanti,företagsengelska,English for business
> 12,Tekninen englanti,teknisk engelska,English for technology
> Add support for non-ISO legacy languages

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/SolkiArvioijaResponse.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusMappingService.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
Suggestion: Instead of mapping inside a class, we dedicate mappings to a mapping service.
This is just a POC:
- Only done with koealusta, but similar pattern could be used in yki as well.
- Tests fails, because the POC is not implemented at tests yet.
- Notice that base is not main
> refactor: mapping service

- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusRepository.kt
- server/src/main/resources/db/migration/V19__change_yki_arvosana_muuttui_type.sql
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
> Arvosanan muutos: rajapintakuvauksessa oli virhe, sisältö on bittimaski kuten kohdassa tarkistusarvioinnin osakokeet. Uusi määrittely:
> tarkistusarvioinnissa muuttuneet arvosanat/osakokeet (kokonaisluku 0–15, tulkitaan bittimaskina 1=pu, 2=ki, 4=ty, 8=py)
> Fix change yki arvosana muuttui data type

- server/src/main/resources/application-untuva.properties
Right now we run every minute, which means our log error alarm has been red for the past few weeks. With this change we should see better when errors happen.
> Run koealusta imports only every hour instead of every minute on untuva

- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusRepository.kt
- Järjestää suoritukset käliin ja csv-exportiin tutkintopäivän mukaan.
- `SELECT DISTINCT ON` vaatii, että haku järjestetään ensisijaisesti sen sarakkeen mukaan, minkä perusteella uniikit rivit tunnistetaan, ja `last_modified` pitää olla kriteerinä, jotta tuplariveistä valittaisiin uusin versio
- Halusin, että haku jossa otetaan mukaan myös versiohistoria tulee samassa järjestyksessä kuin ilman versiohistoriaa, joten kaikkien suoritusten haku piti järjestää samalla tavalla kuin vain uusimpien versioiden haku
> Sort yki suoritukset for UI

- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvExportError.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvParser.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
Old version
```kotlin
csvString.split(lineSeparator)
```
obviously don't take into account newlines inside double quotes.
> fix(yki): support newlines inside double quotes

- e2e/db/database.ts
- e2e/tests/kotoutumiskoulutus/kielitesti-suoritukset.spec.ts
- `yki_arvioija` -taulu puuttui testien välissä suoritettavasta kannan lanauksesta
- KOTO-kielitestin suoritusnäkymän testeihin oli jäänyt ylimääräinen `beforeEach`
> A couple quick fixes to my Playwright brainfarts

- scripts/ensure_aws_secrets.sh
- scripts/start_local_env.sh
- scripts/start_tmux.sh
Enables running e.g. `ensure_aws_secrets.sh idea`. Without this change you could run `source ensure_aws_secrets.sh` in bash but other shells (fish) wouldn't work.
> feat: allow running any command with AWS secrets

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasAuthenticatedService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasException.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/Oppija.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroException.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroLoggingExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
Current logs are not verbous enough to provide the reason for failures when there is something wrong is CAS-flow.
> feat(oppijanumero): add more verbous logging when cas error

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/resources/application.properties
- server/src/main/resources/logback-spring.xml
- server/src/test/kotlin/fi/oph/kitu/KituApplicationTests.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
- server/src/test/resources/application.properties
~This implementation is based on the Spring Data EntityCallback API. It does not conform to what's described on https://wiki.eduuni.fi/pages/viewpage.action?pageId=480353910.~
Lokitetaan manuaalisesti KoealustaServicessä, koska Springin EntityCallback-API ei toimi jos Repositoryn tallennusmetodi on itse toteutettu eikä Springin autogeneroima.
> feat(kotoutumiskoulutus): add audit logging

- server/pom.xml
Bump commons-compress and logback-core and -classic to fix:
- https://osv.dev/vulnerability/GHSA-4265-ccf5-phj5
- https://osv.dev/vulnerability/GHSA-4g9r-vxhx-9pgx
- https://github.com/advisories/GHSA-6v67-2wr5-gvf4
- https://github.com/advisories/GHSA-6v67-2wr5-gvf4
> Security update

- infra/lib/container-repository-stack.ts
- infra/lib/utility-stage.ts
Skannataan imaget automaattisesti ECR:n omalla haavoittuvuusskannerilla kun pusketaan uusi image, ja jos löytyy CRITICAL tai HIGH -tason löydöksiä, lähetetään ne AWS Chatbotin kautta Slackiin. Tämä on siitä hyvä skanni, että esim. imagen base-imagen haavoittuvuudet pitäisi löytyä.
> feat(ecr): enable image scan on push

- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaEntity.kt
- server/src/main/resources/db/migration/V21__update_yki_arvioija_unique_constraint.sql
- server/src/test/kotlin/fi/oph/kitu/yki/YkiArvioijaRepositoryTest.kt
Yki arvioijaan oli lisätty uusia kenttiä, lisätään ne myös `yki_arvioija_is_unique`-constraintiin, jotta duplikaatit tunnistetaan oikein.
> Fix yki arvioija unique constraint

- server/src/main/resources/db/migration/V22__schooloid_not_null.sql
Korjaa bugin, kun kälissä avaa Koto -> Suoritukset ja jos school OID on null. 
- Korjattu lisäämällä tietokantaan tyhjät arvot ja lisäämällä NOT NULL constraint
- Tässä tapauksessa tämän pitäisi riittää, kun arvoa ei käytetä käyttöliittymässä.
- Importterin koodissa [schoolOID on jo not null](https://github.com/Opetushallitus/koto-rekisteri/pull/602/files#diff-faff4682eefe6ff89de50f424a06ff8cb86090afe0c24e1ee9b49b54e87e5a01R17), joten nulleja (tai edes tyhjiä arvoja) ei pitäisi olla
TODO
- Kyllä, mutta ei tässä pullarissa
> fix(kotoutumiskoulutus): school oid not null

- server/src/main/kotlin/fi/oph/kitu/Oid.kt
- server/src/main/kotlin/fi/oph/kitu/jdbc/JdbcCustomConfiguration.kt
- server/src/main/kotlin/fi/oph/kitu/jdbc/OidToStringConverter.kt
- server/src/main/kotlin/fi/oph/kitu/jdbc/StringToOidConverter.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiSuoritus.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/resources/db/migration/V23__add_oid_type.sql
- server/src/main/resources/db/migration/V24__alter_school_oid_to_use_organisaatio_oid_type.sql
- server/src/test/kotlin/fi/oph/kitu/DBIsoOidTest.kt
- server/src/test/kotlin/fi/oph/kitu/OidTest.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
Lisää tuen OID:en validoinnille sekä tietokannan, että sovelluksen tasolla ja toteuttaa näitä käyttäen validaation koealustan suoritusten tuonnin `schooldOID`-kentälle.
Tietokannan tasolla validaatio on toteutettu `DOMAIN`-tyypillä `iso_oid`, jonka `CHECK` suorittaa yksinkertaisen naiivin Regex-pohjaisen tarkistuksen. Tälle domainille on kaksi aliasta, `henkilo_oid` ja `organisaatio_oid`, jotta eri "tyyppiset" OID:t on helpompi eriyttää toisistaan. Näin `school_oid`:lle voidaan antaa tyypiksi `organisaatio_oid` ja esim. oppijanumeroille tmv voidaan myöhemmässä PR:ssa päivittää tyypiksi `henkilo_oid`.
Sovellustason validaatiota varten on toteutettu `Oid`-dataluokka. Tämän alustava toteutus on yksinkertainen "fasadi" (facade) suhteellisen satunnaisesti valikoituneeseen riippuvuuksien kautta …
> Validate received school (organization) OIDs

- server/src/main/resources/logback-spring.xml
Puuttuu vielä automaattitestit tälle, mutta testasin lokaalisti manuaalisesti että `auditLogger`-lokeja ei tule enää konsoliin.
Ks. https://logback.qos.ch/manual/configuration.html#overridingCumulativity
> fix: don't log audit logs to console

- .gitignore
Main is protected so can't push this there directly.
Having local overrides is a bit of an oxymoron for why Mise exists in the first place. However, asdf-awscli build has been broken on Arch for a while now, and I just cannot be bothered to fix it. Local overrides allow me to default to pre-built binaries, so that's an easy way out.
There are some hard-to-debug issues with the aws-cli build script, possibly related to Python version, but these didn't go away with any usual quick fixes I attempted. When enforcing python version via Mise didn't seem to affect the build script python version either, I threw in the towel and just decided to live with it.
Easiest way out is just to use pre-built binaries on Arch, which is easily done by enforcing the non-"ref:" version via a mise.local.toml. …
> [ci skip] ignore .mise.local.toml

- server/pom.xml
Fixes GHSA-4g8c-wm8x-jfhw, CVE-2025-24970
> chore(deps): update netty to 4.1.118.Final

- .github/renovate.json
We used to automatically merge only certain update types. We haven't seen any problems with it, so let's just auto merge all minor and patch updates, regardless of the dependency type.
Example updates this would auto merge: #790 #789
> chore(deps): automerge all minor version updates

- infra/lib/environment-stage.ts
- infra/lib/service-stack.ts
Tämä luo uuden klusterin ja mahdollisesti jättää vanhan roikkumaan, mikä voi johtaa erikoisiin tilanteisiin. Tämä ois hyvä testata erikseen devillä ennen mergeämistä. Tällä hetkellä PR:stä ei voi deployaa ympäristöihin (ja mainin deploy myös yliajaisi ne melko nopeasti) ja meillä ei ole väliaikaisia PR-ympäristöjä. Voisimme periaatteessa luoda väliaikaisia ympäristöjä devitilille jos vaan hoidetaan niiden siivous oikein.
[AWS Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html)
> feat: enable container insights in production

- server/pom.xml
Erikoisesti incubating-paketin versio on erilaisessa muodossa, joten ei voida käyttää samaa propertyä enää.
> chore(deps): update otel semconv to 1.30.0

- infra/lib/db-stack.ts
This should silence this warning: `[Warning at /Prod/Database/DbStack] Performance Insights is enabled on cluster 'DbStack' at cluster level, but disabled for instance 'writer'. However, Performance Insights for this instance will also be automatically enabled if enabled at cluster level. [ack: @aws-cdk/aws-rds:instancePerformanceInsightsOverridden]`
> fix: enable RDS performance insights on writer instance

- scripts/start_otel_collector.sh
- scripts/start_tmux.sh
- scripts/stop_tmux.sh
OpenTelemetry collectorille käynnistysskripti, joka ajetaan tmuxin käynnistyksen yhteydessä dockerissa
Lisätty myös skripti tmuxin pysäyttämiseen `gracefully`:sti. Tätä varten mulla on alias `.zshrc`:ssä. Toi on tarkoituksella nimetty eri tavalla kotorekisteri-start-tmux, jotta autocompletion ei matchais stop-komentoon samalla kirjain-alulla.
```shell
alias stop-kotorekisteri-tmux="$KOTO_REKISTERI/scripts/stop_tmux.sh"
```
> feat(scripts): run otel collector when starting tmux sess

- .mise.toml
Ongelmat:
- awscli päivittyy päivittäin, mikä on paljon churnia lokaaliympäristössä
- käännämme itse awsclin (`ref`-määre versionumerossa) koska binääriversiosta on vain x86-64-julkaisu, ja puristeina emme ole halunneet käyttää Rosetta-x86-emulaatiota mäkeillä
Ratkaisu:
Ajateltiin ensin siirtää `awscli`-riippuvuus kokonaan pois juuresta ja `infra`-hakemiston alle, mutta tajusin että kehitysympäristön skriptit käyttävät sitä. Jotta elämä olisi vähän helpompaa kuitenkin, palataan tässä PR:ssä käyttämään esikäännettyä x86-64-versiota awsclistä.
> Use binary release of awscli

- .github/renovate.json
We don't need this as we don't build awscli from source anymore.
> Remove unused renovate rule

- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvExportError.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvParser.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorRepository.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
- server/src/main/resources/db/migration/V26__create_yki_suoritus_error_table.sql
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockEvent.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusErrorTests.kt
YKI suoritus ei pysähdy kokonaan virheeseen virheeseen enää tämän jälkeen.
Oleellisin muutos:
* Virheenkäsittelyn metodi: https://github.com/Opetushallitus/koto-rekisteri/pull/913/files#diff-d75070358c3906f11656f1a8b987ba3a628743c97f7e8fa0fbf6a849baeb9b9dR13-R30
Muita oleellisia asioita:
* lisätty yki/suoritukset - alle sub domain `errors`, missä on kaikki oleellinen boilerplate. 
* `yki/suoritukset/error/YkiSuoritusErrorEntity.kt` - tietokantataulun - entity luokka
* taulun luontiskripti  `server/src/main/resources/db/migration/V26__create_yki_suoritus_error_table.sql`
* jotta saatu virheet kätevästi ja kaatumatta ulos, lisätty `CsvParser`:iin `convertCsvToData` ohelle `safeConvertCsvToData`, joka palauttaa `Tuple<Data, Error>`. Sitä voi käyttää golang - tyylisesti:
```kotlin
val …
```
> feat(yki): safer error handling table

- server/src/main/kotlin/fi/oph/kitu/yki/YkiScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
Pieni bugi `YkiScheduledTasks`:ssa aiheutti sen, ettei suoritusten tuonnin eräajon viimeisintä aikaleimaa tallennettu tietokantaan ajon päättyessä. Koska aikaleiman oletusarvo oli `null`, ja tämän tulkittiin tarkoittavan "aikojen alusta asti", eräajo käytännössä toi joka kerralla kaikki suoritukset uudelleen.
Tuonti on toteutettu siten, että duplikaatit jätetään huomiotta. Näinollen bugista ei aiheutunut mitään muuta haittaa, kuin hieman lisääntynyttä liikennettä ja hieman tuhlattua suoritinaikaa.
> fix: YKI suoritus import always fetches everything

- infra/lib/service-stack.ts
It currently takes ~four and a half minutes to deploy the koto-rekisteri container to each environment. We can make that faster by fiddling with the load balancer configuration, which by default is very conservative.
Changed settings:
- [New container health check](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/load-balancer-healthcheck.html): from 5 OK responses every 30 seconds to 2 OKs in 5 seconds.
- [New container grace period](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html#sd-networkconfiguration): how long ECS ignores the health checks of a newly started container (to let slow applications start) changed from 60 seconds (CDK default) to 15 seconds.
- [Old container deregistration …
> Make deploys faster

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/Oid.kt
- server/src/main/kotlin/fi/oph/kitu/mock/OidGenerator.kt
Ensimmäinen askel `Oid`-tyyppien käytön parempaan konsistenssiin: vältetään `Oid`-wrapperin instanssien luontia suorilla konstruktorikutsuilla.
Konstruktorin käyttäminen luo suoran riippuvuuden alla olevaan `org.ietf.jgss.Oid`-tyyppiin, ja fakadin tärkein tarkoitus on pitää tällaiset riippuvuudet kapseloituna yhteen paikkaan (= wrapperin sisään). Tämä on tärkeää/hyödyllistä, mikäli alla olevaa Oid-tyyppiä tai sen validaatiota tmv. tarvitsee myöhemmin muuttaa.
Kotlinin dataluokkien `private`-konstruktoreihin liittyy kuitenkin ikävä epäjohdonmukaisuus: automaattisesti generoitu `copy`-konstruktori on julkinen, vaikka kanoninen konstruktori olisi merkitty yksityiseksi. Tämä on muuttumassa tuoreemmissa Kotlin-versioissa, mutta toistaiseksi uusi/tuleva toiminnallisuus on opt-in. Opt-in …
> fix: make private `Oid` constructor actually private

- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvParser.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/OidDeserializer.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/OidSerializer.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusCsv.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusMappingService.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
Käytetään samaa `Oid`-tyyppiä kaikkialla. Preferoidaan wrapper-Oidia.
Wrapperin sisällä olevan `org.ietf.jgss.Oid`-tyypin konstruktorissa on ikävä ominaisuus, että se saattaa heittää poikkeuksen, mikäli sille syötetään epäkelpo arvo. Tämä ei kuitenkaan näy konstruktorin metodikontraktissa mitenkään, vaan virhe lentää ns. "hiljaisesti", joten meillä ei ole mitään tyyppitarkistuksen tai staattisen analyysin apuja varoittamaan tästä. Tämä on kovin "käytännöllistä", koska virheenkäsittelystä ei tarvitse koodia tycitellessä välittää, mutta hieman vähemmän käytännöllistä jos virheenkäsittelystä _haluaisi_ välittää.
Molemmat käyttötapaukset on nyt katettu wrapperin kautta. Tycittelyyn on `Oid.valueOfOrThrow(string) -> Oid ` ja virheenkäsittelyä varten `Oid.valueOf(string) -> Oid?`. Wrapperin …
> Use wrapper-`Oid` everywhere

- infra/lib/service-stack.ts
- scripts/check_env-vars.sh
- scripts/ensure_aws_secrets.sh
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRequest.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRequestMapper.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiResponse.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRestClientConfig.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/CasService.kt
- server/src/main/resources/application-e2e.properties
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-prod.properties
- server/src/main/resources/application-qa.properties
- server/src/main/resources/application-untuva.properties
- server/src/main/resources/application.properties
- server/src/test/kotlin/fi/oph/kitu/koski/KoskiRequestMapperTest.kt
- server/src/test/kotlin/fi/oph/kitu/koski/KoskiServiceTest.kt
- server/src/test/resources/application.properties
- server/src/test/resources/koski-request-with-yleisarvosana.json
- `KoskiService` yki-suoritusten lähettämiseksi Koskeen
- Ei vielä toteutusta suoritusten lähettämiseen käytännössä
- Kosken käyttämiseen sama palvelukäyttäjätunnus kuin Oppijanumerorekisterin käyttöön, joten muutettu propertieseista `kitu.oppijanumero.username` ja `kitu.oppijanumero.password` -> `kitu.palvelukayttaja.username` ja `kitu.palvelukayttaja.password`
> Koski service for sendig YKI suoritus to KOSKI

- server/src/main/kotlin/fi/oph/kitu/Oid.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/OidDeserializer.kt
- server/src/main/kotlin/fi/oph/kitu/jdbc/StringToOidConverter.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/mock/OidGenerator.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusMappingService.kt
- server/src/test/kotlin/fi/oph/kitu/OidTest.kt
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
Siirretään vastuu virheenkäsittelystä parsintalogiikalta kutsujalle, jolloin kutsujan tulee itse tehdä tietoinen valinta miten virhe tulee käsitellä tai voidaanko se jättää käsittelemättä.
Toteutus käyttää tähän Kotlinin standardikijaston `Result<T>`-tyyppiä. Tämä jakaa jonkin verran mielipiteitä, ja varsinaista konsensusta `Result`-tyypin käytön puolesta tai vastaan on hieman hankala löytää. En kuitenkaan halua tuoda tässä kohtaa mukaan mitään fp-mehusteluhassuttelu-kirjastoja uusiksi riippuvuuksiksi, joten tämä lienee tässä yhteydessä ihan järkeenkäypä kokeilu.
Nämä muutokset itsessään ovat melko mitäänsanomattomia (`Oid.valueOfOrThrow(oidStr)` -> `Oid.parse(oidStr).getOrThrow()`), mutta mahdollistavat `Result`-pohjaisen toteutuksen muualla.
Lisää draftailua `Result`-pohjaisesta …
> Use standard `Result<T>` for wrapping OID parsing results

- server/src/main/kotlin/fi/oph/kitu/ResultExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceMock.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
Mahdollistetaan aavistuksen siistimpi virheenhallinta `KoealustaMappingService`:ssa palauttamalla oppijanumeroiden hakuoperaatioista `Result<String>` raa'an `String` sijasta.
Koska `OppijanumeroService` on käytössä vain `KoealustaMappingService`:ssa, tämä muutos on melko suoraviivainen. Parantelin samoilla lämpimillä `OppijanumeroService`:n testejä hieman.
Tämä muutos on seurausta käytännön esimerkistä miksi "piilotetut" virhetilanteet ovat helppo tapa ampua itseään jalkaan; #954 kanssa työskennellessä, `oppijanumero` haku oli pitkään hieman yksinkertaisempi (joskin rikki), sillä en huomannut että `toOppija(user)` voi heittää validaatiovirheen:
```kt
try {
oppijanumeroService.getOppijanumero(toOppija(user))
}
/* snip */
```
_(mitä kaikkia virheitä `catch`:ssa kuuluu käsitellä?)_
Tämän …
> Use `Result<T>` for oppijanumero queries

- server/src/main/kotlin/fi/oph/kitu/ResultExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
Kaikki `Completion.Result` -validaatiofunktiot tekivät käytännössä samaa asiaa. Ainoat muuttuvat osat olivat käytännössä `Result::name` ja `quiz_result_system` pakollisuus. Tämän abstraktointi yleiseen validaatiofunktioon oli suoraviivaista.
Yhtenäistetyn validaatiofunktion lisäksi, oli helpohko homma refaktoroida virheenkäsittely tässäkin tilanteessa palauttamaan `Result<Completion.Result>`, poikkeuksen heittämisen sijaan.
Jotta virheenkäsittely `completionToEntity`:ssa olisi muutenkin yhteneväistä, refaktoroin myös muiden kenttien validaatiot samanmuotoisiksi, lisäämällä `validate`-funktiosta näille sopivat versiot.
Null-tarkistukset oli aiemmin jätetty tekemättä, sillä käytännössä validaatiofunktiosta palautuva arvo on riittävä tae, että arvojen tulisi olla olemassa. Tähän …
> General validation functions for Koealusta quiz completion results

- e2e/fixtures/kotoSuoritus.ts
- e2e/fixtures/ykiSuoritusError.ts
- e2e/tests/yki/yki-suoritukset-error.spec.ts
- e2e/tests/yki/yki-suoritukset.spec.ts
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvExportError.kt
- server/src/main/kotlin/fi/oph/kitu/csvparsing/CsvParser.kt
- server/src/main/kotlin/fi/oph/kitu/dev/YkiController.kt
- server/src/main/kotlin/fi/oph/kitu/mock/YkiSuoritusErrorMock.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorColumn.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorEntity.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
- server/src/main/resources/db/migration/V28__refactor_yki_suoritus_error_table.sql
- server/src/main/resources/templates/yki-suoritukset-virheet.mustache
- server/src/test/kotlin/fi/oph/kitu/csvparsing/CsvParsingTest.kt
- server/src/test/kotlin/fi/oph/kitu/logging/EventLoggerTests.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockEvent.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusErrorTests.kt
* Alkuperäinen ajatus, #988, oli liian monimutkainen, joten sitä ajatusta on suoraviivaistettu tässä
* Pullaria voi olla helpompi lukea commit-kerrallaan:
1. 675accd71a6d8f23c84dd9bbb0391ea1f00a4623 - lisätty että dev-controllerin vastaukseen virheellisiä rivejä
2. 50f3810c8d3e26ca18e356701ef2338893f674ef - kaivetaan virheellinen kenttä lokitietoihin
3. 5611a84502ea387f87721b1bed832493ea928632 - **rikkova commit:** refaktoroitu (sql) taulu. SQL sisältää unique constraint, joten duplikaattirivejä ei synny, vaan aiheuttaa virheen, mikä lokittuu oteliin
4. 72df04fa791c42ab5f0b4a7d34f6852282680ac2 - korjattu entity-luokka
5. 19b4fb136dd7b9342785697f427b4d1669ff1f70 - tallennetaan virheelliset rivit. csv-parsiminen on nyt minimalistinen
6. 77ea07e5e7397b826dca1c5dbb03666088769c54 - korjattu …
> feat(yki) UI cleaner UI table version 2

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroException.kt
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroService.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceMock.kt
- server/src/test/kotlin/fi/oph/kitu/oppijanumero/OppijanumeroServiceTests.kt
Tehdään datan parsinta ja mankelointi haluttuun muotoon mahdollisimman aikaisin, ettei validoinnin tarve valu muille luokille. Koodi pysyy siistimpänä, kun `Oid` muotoinen data on `Oid` eikä `String` koko käsittelyn ajan.
> Return oppijanumero as `Oid` from `OppijanumeroService`

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiSuoritus.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/main/kotlin/fi/oph/kitu/mock/KielitestiMock.kt
- server/src/main/resources/db/migration/V31__validate_koto_suoritus_oppijanumero_oid.sql
Samat setit kuin YKI suorituksille; validoidaan OID tyyppiset kentät myös tietokannassa. Aikaisempien refaktorointien vuoksi tämä on KOTO:n osalta koodin puolella huomattavan paljon kivuttomampaa, kuin YKI:n tapauksessa.
Tietokannassa olevan datan osalta ei valitettavasti voi sanoa samaa. Näitä muutoksia ei voida mergetä, sillä migraatio ei tällä hetkellä menisi testiympäristössä läpi. Tuotannossa ei vielä ole KOTO-suorituksia, joten siellä ei ole ongelmia.
Testiympäristössä on tällä hetkellä tietokannassa rivejä, joissa `oppijanumero` on sellainen merkkijono, ettei se ole kelvollinen Oid (esim. tyhjä merkkijono). Nämä rivit tulee korjata (mielellään lähtöjärjestelmässä), jotta migraatiot voidaan ajaa sisään. Teoriassa myös rivien poistaminen on ehkä vaihtoehto, sillä koalustaintegraation …
> Use Oid types for Koto suoritukset in the database

- server/src/main/kotlin/fi/oph/kitu/koski/Koodisto.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRequestMapper.kt
- server/src/test/resources/koski-request-example.json
- server/src/test/resources/koski-request-with-yleisarvosana.json
YKI tutkintojen eri osakokeista ei päätellä koko tutkinnon hyväksymistä/hylkäämistä, joten selkeyden vuoksi muutetaan opiskeluoikeuden tila hyväksytysti suoritettu -> päättynyt.
> Change KOSKI opiskeluoikeuden tila from hyvaksytty to paattynyt

- e2e/README.md
- e2e/fixtures/baseFixture.ts
- e2e/models/dbSchedulerPage.ts
- e2e/tests/yki/yki-suoritukset-error.spec.ts
- server/src/main/resources/application-e2e.properties
- Ennen YkiSuoritusError - testi alkoi YkiSuoritus - sivulta, jossa oletettiin, että import on ajettu. (Oletus on tehty alustamalla tietokanta testeissä sopivasti).
- Nyt se osuus on korvattu, ja e2e-testi klikkaa Runia importissa.
- Tässä versiossa myöskin e2e putki ajaa importit 60min välein. Väli on valittu tarkoituksella, jotta importin seuraava ajo ei osu samalle ajalle kuin kuin e2e-testin ajo. Ja jos osuu, niin testissä on silloin jotain muuta vikaa.
- Lisätty e2e/README.md jotain komentoja, e2e testaamista varten
- Lokaalisti testasessa testi kerran hajosi, kun käliin oli ilmestynyt ylimääräinen RefreshCircle, ja mun käyttämä selectori löytää myös sen. En oo saanu toistettua sitä.
> feat(e2e): start ykisuorituserror e2e test from import 

- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
I think the only change here is that the code doesn't depend on the order of the items returned from `find(distinct = true)`. Not sure why that started failing suddenly.
> Fix failing test

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/logging/OpenTelemetryExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockEvent.kt
- server/src/test/kotlin/fi/oph/kitu/logging/OpenTelemetryTestConfig.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusErrorTests.kt
WIP: Base on `refactor/csv-parser-otel-tracing`, jotta näkee mitä kuuluu tähän tehtävään
Tän pullarin pihvi, eli lokeissa näkyy koko flow spaneissa, kun ajetaan import.
Tätä pullaria voi käyttää templatena jos haluaa jatkossa refaktoroida eventtejä otel-traceiksi. Tehtävä työ on
```diff
-import org.slf4j.Logger
-import org.slf4j.LoggerFactory
+import io.opentelemetry.api.trace.Tracer
class YkiService(
+  val tracer: Tracer
) {
-  private val logger: Logger = LoggerFactory.getLogger(javaClass)
fun importYkiSuoritukset() =
-  logger
-    .atInfo()
-    .withEventAndPerformanceCheck { event ->
// Täällä on sovelluksen koodi
-    }.apply {
-      addDefaults("yki.importSuoritukset")
-      addDatabaseLogs()
-    }.getOrThrow()
+  tracer
+    .spanBuilder("yki.importSuoritukset")
+ …
```
> refactor(yki): use opentelemetry in yki suoritukset import

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/logging/OpenTelemetryExtensions.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
- server/src/test/kotlin/fi/oph/kitu/logging/MockEvent.kt
- server/src/test/kotlin/fi/oph/kitu/logging/OpenTelemetryTestConfig.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiServiceTests.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusErrorTests.kt
Jos haluaa opentelemetry spanit alkamaan taskien scheduloinnista, niin se pitää tehdä näin:
```kotlin
@Bean
fun dailyImport(ykiService: YkiService): Task<Instant?> =
// ensin luodaan span, joka ajetaan aina kun Beania kutsutaan. 
// Se taitaa olla ainoastaan jos sovellus käynnistetään?
tracer
.spanBuilder("Beans.dailyImport.init")
.startSpan()
.use {
Tasks
.recurring("YKI-import", ExtendedSchedules.parse(ykiImportSchedule), Instant::class.java)
.initialData(Instant.EPOCH)
.executeStateful { taskInstance, _ ->
// Tämä konkteksti alkaa kun Scheduler API päättää, että nyt pitää suorittaa tämä block
// Tämä ei ajallisesti liity beanin triggeröintiin, joten tarvitaan uusi span
tracer
.spanBuilder("Beans.dailyImport.execute")
.startSpan()
.use { …
```
> feat(yki): add traces to scheduledtasks

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
- server/src/test/resources/application-local.properties
Vältetään hieman boilerplatea testeissä käyttämällä Springin luomaa service-instanssia.
> Refactor: Reduce test init boilerplate from Koealusta tests

- scripts/start_local_env.sh
Misen `experimental` -asetusta ei ole enää tarpeen asettaa päälle, sillä Misen `npm`-backend ei enää tätä vaadi.
Jos/kun on aiemmin asettanut `mise settings set experimental true` tai ajanut `start_local_env.sh`-skriptin, `experimental` -asetus on pysyvästi päällä. Jos asetuksen haluaa pois päältä, voi ajaa komennon:
```sh
mise settings set experimental false
```
> Mise experimental mode is no longer needed

- server/pom.xml
- server/src/main/resources/application.properties
Hyvin pelkistetty automaagisesti konfiguroitu Swagger UI setup. Näyttää kaikki muotoa `/DOMAIN/api/**/*` olevat API-endpointit Swagger UI:ssa. Itse UI oletuksena saatavilla polussa `/swagger-ui.html`
Meillä on tällä hetkellä yksi endpoint; YKI-CSV -export, `GET /yki/api/suoritukset`. Tämä näkyy seuraavanlaisesti:
> feat: add basic swagger ui with springdoc starter

- server/pom.xml
- server/src/main/kotlin/fi/oph/kitu/oppijanumero/HttpClientConfig.kt
CAS-autentikaatiota käyttävät kutsut käyttävät [java.net.HttpClient](https://docs.oracle.com/en/java/javase/21/docs/api/java.net.http/java/net/http/HttpClient.html)-kirjastoa Springin RestTemplaten/RestClientin sijaan. Se pitää instrumentoida erikseen että saadaan kutsut mukaan traceihin.
> Add OpenTelemetry instrumentation to java.net HttpClient

- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaMappingService.kt
- server/src/test/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaServiceTests.kt
Poistettu suoritusten validaatiosta virheiden luonti siinä tapauksessa, että kutsumanimi tai oppijanumero puuttuu, koska niistä luodaan virheet jo oppijan validaatiossa tai oppijanumeropalvelua kutsuttaessa.
> Remove duplicate koto failures

- server/src/main/kotlin/fi/oph/kitu/mock/YkiSuoritusMock.kt
- server/src/test/kotlin/fi/oph/kitu/yki/YkiSuoritusRepositoryTest.kt
Copied values from https://github.com/Opetushallitus/koto-rekisteri/actions/runs/15152297170/job/42600500336
Now it, with thesese values, it seems to be reproduced locally
You can reproduce the error by running the test eg over 100 times
```kotlin
// @Test
@ParameterizedTest
@ValueSource(
ints = [
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30,
31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 75, 78, 79, 80, 81, 82, 83, 84, 85,
86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
],
)
fun `test`(runNumber: Int) { ... }
```
> test CI/CD error

- e2e/models/kotoutumiskoulutus/KielitestiSuorituksetPage.ts
- e2e/tests/kotoutumiskoulutus/kielitesti-suoritukset.spec.ts
- e2e/util/arrays.ts
- server/src/main/kotlin/fi/oph/kitu/html/DisplayTable.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiSuoritusColumn.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiSuoritusErrorColumn.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KielitestiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktIlmoittautuneet.kt
- server/src/main/kotlin/fi/oph/kitu/webmvc/EnumFromUrlParamsParsingConfig.kt
- server/src/main/kotlin/fi/oph/kitu/webmvc/WebConfig.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiViewController.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/YkiArvioijaColumn.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/error/YkiArvioijaErrorColumn.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/YkiSuoritusColumn.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorColumn.kt
- server/src/main/resources/templates/koto-kielitesti-suoritukset.mustache
- server/src/main/resources/templates/koto-kielitesti-virheet.mustache
- server/src/main/resources/templates/yki-arvioijat-virheet.mustache
- server/src/main/resources/templates/yki-arvioijat.mustache
- server/src/main/resources/templates/yki-suoritukset-virheet.mustache
- server/src/main/resources/templates/yki-suoritukset.mustache
Nämä muutokset pyrkivät vähentämään query parametrien parsintaan liittyviä epäselvyyksiä/maagisuuksia tekemällä muunnoksissa käytetyt merkkijonoarvot eksplisiittisemmin näkyviksi ja uudelleennimeämällä luokkia/metodeja hieman kuvaavammilla nimillä.
Nykyinen toteutus Enum-String-Enum -muunnoksille query parametreja varten sisältää joitain epäselvyyksiä. Toteutuksessa on jonkin verran yllättäviä, "tämä pitää vain tietää" -piirteitä. Muunmuassa `lowercaseName` ja (de)serialisionnin välinen yhteys ei ole juuri mitenkään dokumentoitu, eikä esim. "find all usages" -tyylisillä IDE ominaisuuksilla ole mahdollista huomata `Enum::name` ja `WebConfig.kt`:n liittyvän mitenkään toisiinsa.
Tämän vuoksi on esim. helpohkoa vahingossa päätyä rikkomaan sarakkeiden järjestämislinkit eri näkymissä, melko …
> Make enum variant parsing from query parameters slightly less magical

- server/src/main/kotlin/fi/oph/kitu/koski/KoskiScheduledTask.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/tehtavapankki/TehtavapankkiScheduledTasks.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiScheduledTasks.kt
This should not change behaviour but documents the property better. Also remove the `matchIfMissing` argument since we always use its default value.
Ref: https://docs.spring.io/spring-boot/api/java/org/springframework/boot/autoconfigure/condition/ConditionalOnBooleanProperty.html
> Use the new Spring Boot 3.5.0 @ConditionalOnBooleanProperty

- server/src/main/resources/logback-spring.xml
According to [this CloudWatch query](https://515966535475-ihzxz2j3.eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/KituService/log-events/kitu$252Fweb$252F8dcea7019b054fae840fe3b3c5a1b2bc$3Fstart$3D1748048400000$26filterPattern$3Dprincipal$26end$3D1748052000000) we're using the audit log file appender in deployment environments, even though we tried to disable it there with the `additivity=false` attribute. After re-reading [the logback documentation](https://logback.qos.ch/manual/configuration.html#overridingCumulativity) again I think that attribute only helps if the other appender(s) are higher in the configuration hierarchy. In our case they're at the same level (notwithstanding Spring profiles), so my assumption is that additivity has no …
> Audit logging: force disable file appender in deployment environments

- infra/lib/service-stack.ts
I'm trying to figure out why untuva doesn't have any traces. This might help.
> Send ADOT logs to CloudWatch

- .mise.toml
Jostain syystä mise ei oo päivittänyt tähän, ja se hajotti ainakin tän #1498
> chore(mise): upgrade maven to 3.9.11

- infra/lib/accounts.ts
- infra/lib/environment-stage.ts
- infra/lib/service-stack.ts
We're in a weird situation where the application URL path component is different in untuva vs. test and prod. This will disappear soon but for now, let's do this.
> fix(infra): parametrize health check path

- .github/renovate.json
This is a precaution against supply-chain attacks like https://www.bleepingcomputer.com/news/security/npm-package-is-with-28m-weekly-downloads-infected-devs-with-malware/
Supersedes #1597 because I failed to read the documentation properly.
Ref: https://docs.renovatebot.com/config-validation/#validation-of-renovate-config-change-prs
> security: wait 3 days before automerging dependency updates

- .github/workflows/_deploy-env.yml
- .github/workflows/build.yml
This might be a bug in the AWS credentials action.
> ci: try to fix aws credentials issue

- infra/lib/koski-audit-logs-integration-stack.ts
- server/src/main/kotlin/fi/oph/kitu/kotoutumiskoulutus/KoealustaService.kt
- server/src/main/kotlin/fi/oph/kitu/logging/AuditLogger.kt
- server/src/main/kotlin/fi/oph/kitu/yki/YkiService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/arvioijat/error/YkiArvioijaErrorService.kt
- server/src/main/kotlin/fi/oph/kitu/yki/suoritukset/error/YkiSuoritusErrorService.kt
Lähetetään vain CloudWatch -eventit lambdalle, jotka sisältää sanan `operation`. Käytännössä #1666 - muutosten myötä ainoastaan 
https://github.com/Opetushallitus/koto-rekisteri/pull/1666/files#diff-e91b75094973745b11911849ba53a6a9dd306fe939a89a9a8263fee4a50bab1fR45-R51
log-overloadit viedään lambdaan. Pitäisiköhän niihin merkata/kommentoida jotenkin, näin tapahtuu? Tämä logiikka on aika implisiiittinen / ja ehkä hiljaista tietoa, niin siitä vois jotenkin huomauttaa koodissa
> feat: get only cloudwatch events containing word operation

- e2e/tests/vkt/vkt-suoritukset.spec.ts
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiException.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRequestMapper.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRestClientConfig.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiScheduledTask.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiService.kt
- server/src/main/kotlin/fi/oph/kitu/mock/OidGenerator.kt
- server/src/main/kotlin/fi/oph/kitu/mock/VktSuoritusMockGenerator.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepository.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/resources/application-local.properties
- server/src/main/resources/application-localkoski.properties
- server/src/test/kotlin/fi/oph/kitu/koski/KoskiRequestMapperTest.kt
- server/src/test/kotlin/fi/oph/kitu/koski/KoskiServiceTest.kt
- **Tue lokaalin Kosken käyttöä rinnalla kehitykseen:**
- **Siirrä vkt-suoritukset Koskeen kokonaisuuksina yksittäisten tietokannassa olevien suoritusrivien mukaan**
> OPHKOTO-18: Siirrä vkt-suoritukset kokonaisuuksina Koskeen yksittäisten ilmoittautumisten sijaan

- server/src/main/kotlin/fi/oph/kitu/html/Json.kt
- server/src/main/kotlin/fi/oph/kitu/html/ViewMessage.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiErrorRepository.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiRequestMapper.kt
- server/src/main/kotlin/fi/oph/kitu/koski/KoskiService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VKTSuoritusRepository.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritus.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusEntity.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktSuoritusService.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/VktViewController.kt
- server/src/main/kotlin/fi/oph/kitu/vkt/html/VktSuorituksenTiedot.kt
- server/src/main/resources/db/migration/V44__split_koski_error_entity.sql
- server/src/test/kotlin/fi/oph/kitu/koski/KoskiRequestMapperTest.kt
- **Splittaa KOSKI-siirtovirheiden tunniste kahteen kenttään**
- **Näytä json-muotoiset KOSKI-virheet selkeämmässä muodossa**
- **Kytke KOSKI-siirtopyyntö takaisin päälle, kun osakokeelle on annettu arvosana**
- **Näytä karkea tieto KOSKI-siirron tilasta**
- **Älä yritä lähettää Koskeen suoritusta, josta puuttuu arviointeja**
> OPH-KOTO17: Korjauksia KOSKI-siirtoihin ja parannuksia virheiden näyttämiseen

- infra/lib/koski-audit-logs-integration/types.ts
- server/src/main/kotlin/fi/oph/kitu/Oid.kt
- server/src/main/kotlin/fi/oph/kitu/TimeConfig.kt
- server/src/main/kotlin/fi/oph/kitu/logging/AuditLogger.kt
- server/src/test/kotlin/fi/oph/kitu/OidTest.kt
- server/src/test/kotlin/fi/oph/kitu/logging/AuditLoggerTests.kt
- server/src/test/resources/application.properties
OID ei ollut serialisoitu oikein. Tehty sille samalla AuditLoggerille ja Oidin serialisoinnille testit. Käytetty springing contekstia AuditLoggerissa, koska toteutus pakottaa siihen. Laitettu kello omaan papuun, jotta `Instant.now()` voidaan palauttaamaan kovakoodattu kellonaika
> fix: audit log
